root = "."
tmp_dir = "tmp"

[build]
cmd = "go mod tidy && go build -o ./tmp/notification-batch ./cmd/batch"
bin = "tmp/notification-batch"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
